### DISCUSSION TITLE
CDN-CGI 연결 오류

### DISCUSSION THREAD

**Discussion by woonjjang** [team-durumi/theme-wwm#16] [Q&A] [answered]
```
cfImagePrefix: 'https://kctu-photo.durumi.io/cdn-cgi/image'
cfImageStyles:
  thumb: 'fit=scale-down,width=300'
  full: 'fit=scale-down,width=1920'
```
theme-wwm에서도 테스트 확인을 위해서 https://kctu-photo.durumi.io/ 로 잡아놓고 테스트했는데, 
wwm 혹은 photo.kctu.org 처럼 production 환경에서는 사진경로를 우리쪽 CDN으로 연결해 놓을 수 없는 것일까요 ?
