### ISSUE TITLE
상설 전시섹션 - 세부 (01, 02)

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/theme-wwm#18]
전시섹션 - 세부
| - 레이아웃 1 (펼침형)
| - 레이아웃 2(액자형)

[Data]
- md file 에서 섹션세부의 영역마다 레이아웃을 지정해 주는 값과 레이아웃 구분이 필요함. 

[레이아웃 1 (펼침형)]
- 예전에 전시 레이아웃 샘플 https://github.com/team-durumi/durumi-react/tree/master/public/prototype/components 
- 더 필요한 레이아웃이 추가 될 수 있음. 

[레이아웃2 (액자형)]
- 부분에 지정하는게 아니라 섹션에 지정하면 전체가 액자형으로 열리는 게 필요
- [ ] 전시02 템플릿에 스크립트 붙이기

**Comment by suncrud** [comment]
https://github.com/team-durumi/theme-wwm/discussions/19 에서 exhibition/ex-01/section-01/index.md 이렇게 사용하는 이유를 피력하셨음에도 불구하고

그것에 반하는 

이런 코밋을 하는 만행을 저질렀습니다...
https://github.com/team-durumi/theme-wwm/commit/5772b8335a70f893a4acf0db0a24e15adfe9c391

**Comment by woonjjang** [comment]
#19 는 discussion 이니까. 이렇게 저렇게 시도하는게 중요 !! 
필요한 경우가 생기면 폴더 만들어서 하겠습니다.

**Comment by woonjjang** [comment]
```
---
title: title_sample
subtitle: subtitle
date: 2021-12-21
summary: 불어 우리는 품으며, 천고에 풍부하게 석가는 때문이다. 때에, 반짝이는 희망의 안고, 바이며, 스며들어 목숨을 있으며, 길을 아름다우냐? 소리다.이것은 인생에 인생에 바로 운다. 열락의 아니더면, 방황하여도, 청춘은 귀는 있으랴?
weight: 6
image: https://wwm3.s3.ap-northeast-2.amazonaws.com/exhibition/exbition01/s0-item1.png
layout: view01
resources:
- partial_layout: diagonal-2
  components: 
  - name: item-01
    params:
      icon: photo
    src: https://wwm3.s3.ap-northeast-2.amazonaws.com/exhibition/exbition01/s0-item1.png
    description: Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque praesentium nisi officiis maiores quia sapiente totam omnis vel sequi corporis ipsa incidunt reprehenderit recusandae maxime perspiciatis iste placeat architecto, mollitia delectus ut ab quibusdam. 
    target: /items/exhibition/exbition01/s0-item1
  - name: item-02
    params:
      icon: photo
    src: https://wwm3.s3.ap-northeast-2.amazonaws.com/exhibition/exbition01/s0-item1.png
    description: Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque praesentium nisi officiis maiores quia sapiente totam omnis vel sequi corporis ipsa incidunt reprehenderit recusandae maxime perspiciatis iste placeat architecto, mollitia delectus ut ab quibusdam.
    target: items/exhibition/exbition01/s1-item2
- partial_layout: full-1
  components: 
    - name: item-03
      params:
        icon: photo
      src: https://wwm3.s3.ap-northeast-2.amazonaws.com/exhibition/exbition01/s0-item1.png
      description: Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque praesentium nisi officiis maiores quia sapiente totam omnis vel sequi corporis ipsa incidunt reprehenderit recusandae maxime perspiciatis iste placeat architecto, mollitia delectus ut ab quibusdam. 
      target: /items/exhibition/exbition01/s2-item1
- partial_layout: horizontal-2
  components: 
    - name: item-04
      params:
        icon: photo
      src: https://wwm3.s3.ap-northeast-2.amazonaws.com/exhibition/exbition01/s0-item1.png
      description: Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque praesentium nisi officiis maiores quia sapiente totam omnis vel sequi corporis ipsa incidunt reprehenderit recusandae maxime perspiciatis iste placeat architecto, mollitia delectus ut ab quibusdam. 
      target: /items/exhibition/exbition01/s3-item1
    - name: item-04
      params:
        icon: photo
      src: https://wwm3.s3.ap-northeast-2.amazonaws.com/exhibition/exbition01/s0-item1.png
      description: Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque praesentium nisi officiis maiores quia sapiente totam omnis vel sequi corporis ipsa incidunt reprehenderit recusandae maxime perspiciatis iste placeat architecto, mollitia delectus ut ab quibusdam. 
      target: /items/exhibition/exbition01/s3-item1     
- partial_layout: horizontal-4    
  components: 
    - name: item-04-01
      params:
        icon: photo
      src: https://wwm3.s3.ap-northeast-2.amazonaws.com/exhibition/exbition01/s0-item1.png
      description: Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque praesentium nisi officiis maiores quia sapiente totam omnis vel sequi corporis ipsa incidunt reprehenderit recusandae maxime perspiciatis iste placeat architecto, mollitia delectus ut ab quibusdam. 
      target: /items/exhibition/exbition01/s4-item1
    - name: item-04-02
      params:
        icon: photo
      src: https://wwm3.s3.ap-northeast-2.amazonaws.com/exhibition/exbition01/s0-item1.png
      description: Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque praesentium nisi officiis maiores quia sapiente totam omnis vel sequi corporis ipsa incidunt reprehenderit recusandae maxime perspiciatis iste placeat architecto, mollitia delectus ut ab quibusdam. 
      target: /items/exhibition/exbition01/s4-item1     
    - name: item-04-03
      params:
        icon: photo
      src: https://wwm3.s3.ap-northeast-2.amazonaws.com/exhibition/exbition01/s0-item1.png
      description: Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque praesentium nisi officiis maiores quia sapiente totam omnis vel sequi corporis ipsa incidunt reprehenderit recusandae maxime perspiciatis iste placeat architecto, mollitia delectus ut ab quibusdam. 
      target: /items/exhibition/exbition01/s4-item1
    - name: item-04-4
      params:
        icon: photo
      src: https://wwm3.s3.ap-northeast-2.amazonaws.com/exhibition/exbition01/s0-item1.png
      description: Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque praesentium nisi officiis maiores quia sapiente totam omnis vel sequi corporis ipsa incidunt reprehenderit recusandae maxime perspiciatis iste placeat architecto, mollitia delectus ut ab quibusdam. 
      target: /items/exhibition/exbition01/s4-item1     
---
```
