### ISSUE TITLE
banner--section-single.html

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/theme-wwm#20]
![card-sticky](https://user-images.githubusercontent.com/6022883/146866008-aa5ee6b8-52e4-4298-b311-ab06eaf85a21.png)

페이지마다 붙어있는 영역(이름 바꿔도 됨. 나는 card-sticky.html)로 하려다 페이지별 분기를 쳐야해서 한계 봉착
md file에 이미지링크 / 제목 / summary / itemlink 가 들어가야함. (교육, 전시처럼 콘텐츠 영역이 풍부하고 카드 썸네일이 큰 것들이 있는 화면에는 없음.)

전시 붙이고, 요것 좀 맡아주세요.

**Comment by woonjjang** [comment]
```
---
title: 관람예약 및 안내
date: 2011-11-17
layout: section_single
banner:
  title:
  summary:
  imageLink:
  itemLink:
---
```
